# Generated by Django 4.0.2 on 2022-02-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_account_holder_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance_amount',
            new_name='account_balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
