# Generated by Django 4.0.2 on 2022-02-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_rename_balance_amount_account_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
